### ISSUE TITLE
Templating to display data related to list of events

### ISSUE THREAD

**Issue by matthyy** [ekino/expresso#4]
Given the list of events defined in issues: https://github.com/ekino/expresso/issues/3

We need to design a html template to display all information related to those events in a structured manner. The choice of template engine is not set yet

**Comment by pebie** [comment]
I choose react template to replace Handlebars
Why ? : 

- Powerfull tools
- Tiny configuration
- Work for node/browser
- CSS/SCSS less (syle component)
- Front team can help us to create a more powerfull tool
- Global framework knowlegde inside team
- Resilient and easy to maintain

May I close this issue ?

**Comment by pebie** [comment]
Done
